[build-system]
build-backend = "mesonpy"
requires = ["meson-python", "ninja", "numpy>=1.26.0"]

[project]
name = "edengnn"
version = "0.1.1"
authors = [
  { name="Xiwen Li", email="lixiwen2718@gmail.com" },
]
dependencies = [
    "numpy",
    "torch >= 2.0.0",
    "torch_geometric",
    "e3nn",
    "lightning",
    "meson",
    "vesin",
    "wandb",
    "omegaconf",
    "matplotlib"
]
description = "EdenGNN: An Efficient E(3)-Equivariant Graph Neural Network for Charge Density Prediction"